// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://levudgwbzmiqvlldszfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldnVkZ3diem1pcXZsbGRzemZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODk0MDUsImV4cCI6MjA3MTQ2NTQwNX0.h2X8WA217PU9pI4ZJNgH0UxTpvrwx5_a5o_7Czr2DUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});